name: vtt-innovation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas>=1.5.0
  - numpy>=1.22.0
  - pydantic>=1.10.0
  - tqdm>=4.65.0
  - matplotlib>=3.6.0
  - networkx>=3.0
  - seaborn>=0.12.0
  - scikit-learn>=1.2.0
  - jupyter>=1.0.0
  - notebook>=6.5.0
  - pip>=23.0
  - pip:
    - langchain-openai>=0.0.1
    - openai>=1.0.0 