# fly.qdrant.toml
app = "qdrant-server-wantsomechips"
primary_region = "fra"

[build]
dockerfile = "dockerfile-qdrant"

[mounts]
source = "qdrant_data"
destination = "/qdrant/storage"

[env]
QDRANT__SERVICE__HOST = "::"
QDRANT__STORAGE__DIR = "/qdrant/storage"

[[services]]
internal_port = 6333
protocol = "tcp"
